name: SkyPvP
version: 1
api-version: 1.21
main: me.rejomy.skypvp.SkyPvP
commands:
  buildarea:
    permission: buildarea.command
    permission-message: "You dont have buildarea.command permission!"
  createteleport:
    permission: nmsp.teleport
  buyernmsp:
  rtpisland:
depend:
  - packetevents
softdepend:
  - worldguard